export enum RoleName {
  ADMIN = "ADMIN",
  CLEANER = "CLEANER",
  CUSTOMER = "CUSTOMER",
}

export enum UserEvent {
  REGISTRATION_STARTED = "REGISTRATION_STARTED",
  USER_CREATED = "USER_CREATED"
}

export enum RegistrationStep {
  AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION",
  CREATING_USER = "CREATING_USER",
  CREATING_PROFILE = "CREATING_PROFILE",
  LOGIN_USER = 'LOGIN_USER',
  REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
}
