// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface PublicUser {
  id: number;
  userName: string;
  email: string;
}

export interface PrivateUser {
  id: number;
  userName: string;
  role: string;
  tokenVersion: number;
  password: string;
}

export interface FindOneUserRequest {
  userName?: string | undefined;
  email?: string | undefined;
  id?: number | undefined;
}

export interface ActionResponse {
  success: boolean;
  id: number;
}

export interface CreateRequest {
  email: string;
  userName: string;
  password: string;
  role: string;
}

export interface UserServiceClient {
  createCandidate(request: CreateRequest): Observable<ActionResponse>;

  findPrivateUser(request: FindOneUserRequest): Observable<PrivateUser>;

  findPublicUser(request: FindOneUserRequest): Observable<PublicUser>;
}

export interface UserServiceController {
  createCandidate(request: CreateRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  findPrivateUser(request: FindOneUserRequest): Promise<PrivateUser> | Observable<PrivateUser> | PrivateUser;

  findPublicUser(request: FindOneUserRequest): Promise<PublicUser> | Observable<PublicUser> | PublicUser;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createCandidate", "findPrivateUser", "findPublicUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
