// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: projection.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";

export interface ErrorDetails {
  code: number;
  field: string;
  context: string;
}

export interface OrderServiceResponce {
  success: boolean;
  message: string;
  error: ErrorDetails | undefined;
}

export interface ProjectionServiceClient {
}

export interface ProjectionServiceController {
}

export function ProjectionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProjectionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProjectionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECTION_SERVICE_NAME = "ProjectionService";
