FROM node:22.19.0-alpine 
# alpine версия весит меньше и работает быстрее

WORKDIR /app
RUN apk add --no-cache protobuf
# 1. Копируем конфиги управления проектом
COPY package*.json ./
COPY nest-cli.json tsconfig*.json ./

# 2. Устанавливаем зависимости (они общие для монорепозитория)
RUN npm install

# 3. Аргумент сервиса (user или order)
ARG SERVICE
ENV SERVICE=${SERVICE}

# 4. Копируем только нужные либы и само приложение
COPY libs/common ./libs/common
COPY libs/${SERVICE} ./libs/${SERVICE}
COPY apps/${SERVICE} ./apps/${SERVICE}

# RUN npm run proto:generate --service=${SERVICE} && \
#     if [ -f "apps/${SERVICE}/prisma/schema.prisma" ]; then \
#         npm run prisma:generate --service=${SERVICE}; \
#     fi

# RUN npm run proto:generate --service=${SERVICE} 
    # npm run prisma:generate --service=${SERVICE} 
    # npm run prisma:migrate:deploy --service=${SERVICE}


CMD ["sh", "-c", "npx nest start ${SERVICE} --watch "]