// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apps/proto/customer/v1/customer.proto

package customerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int32                 `protobuf:"varint,1,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	Id            *int32                 `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_apps_proto_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_apps_proto_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerRequest) GetUserId() int32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetCustomerRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_apps_proto_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_apps_proto_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_apps_proto_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Customer) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Customer) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Customer) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_apps_proto_customer_v1_customer_proto protoreflect.FileDescriptor

const file_apps_proto_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	"%apps/proto/customer/v1/customer.proto\x12\vcustomer.v1\"X\n" +
	"\x12GetCustomerRequest\x12\x1b\n" +
	"\x06userId\x18\x01 \x01(\x05H\x00R\x06userId\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x05H\x01R\x02id\x88\x01\x01B\t\n" +
	"\a_userIdB\x05\n" +
	"\x03_id\"l\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName2X\n" +
	"\x0fCustomerService\x12E\n" +
	"\vGetCustomer\x12\x1f.customer.v1.GetCustomerRequest\x1a\x15.customer.v1.CustomerBAZ?github.com/Denisx1/Some-micro/apps/proto/customer/v1;customerv1b\x06proto3"

var (
	file_apps_proto_customer_v1_customer_proto_rawDescOnce sync.Once
	file_apps_proto_customer_v1_customer_proto_rawDescData []byte
)

func file_apps_proto_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_apps_proto_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_apps_proto_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_proto_customer_v1_customer_proto_rawDesc), len(file_apps_proto_customer_v1_customer_proto_rawDesc)))
	})
	return file_apps_proto_customer_v1_customer_proto_rawDescData
}

var file_apps_proto_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_proto_customer_v1_customer_proto_goTypes = []any{
	(*GetCustomerRequest)(nil), // 0: customer.v1.GetCustomerRequest
	(*Customer)(nil),           // 1: customer.v1.Customer
}
var file_apps_proto_customer_v1_customer_proto_depIdxs = []int32{
	0, // 0: customer.v1.CustomerService.GetCustomer:input_type -> customer.v1.GetCustomerRequest
	1, // 1: customer.v1.CustomerService.GetCustomer:output_type -> customer.v1.Customer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_proto_customer_v1_customer_proto_init() }
func file_apps_proto_customer_v1_customer_proto_init() {
	if File_apps_proto_customer_v1_customer_proto != nil {
		return
	}
	file_apps_proto_customer_v1_customer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_proto_customer_v1_customer_proto_rawDesc), len(file_apps_proto_customer_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_proto_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_apps_proto_customer_v1_customer_proto_depIdxs,
		MessageInfos:      file_apps_proto_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_apps_proto_customer_v1_customer_proto = out.File
	file_apps_proto_customer_v1_customer_proto_goTypes = nil
	file_apps_proto_customer_v1_customer_proto_depIdxs = nil
}
