// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: registration.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface Empty {
}

export interface InitRequest {
  email: string;
  userName: string;
  password: string;
  role: string;
}

export interface FinalizeRequest {
  actionToken: string;
}

export interface RegistrationServiceClient {
  initRegistration(request: InitRequest): Observable<Empty>;

  confirmRegistration(request: FinalizeRequest): Observable<Empty>;
}

export interface RegistrationServiceController {
  initRegistration(request: InitRequest): Promise<Empty> | Observable<Empty> | Empty;

  confirmRegistration(request: FinalizeRequest): Promise<Empty> | Observable<Empty> | Empty;
}

export function RegistrationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["initRegistration", "confirmRegistration"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RegistrationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RegistrationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REGISTRATION_SERVICE_NAME = "RegistrationService";
