// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface ConfirmRegistrationRequest {
  actionToken: string;
}

export interface ActionResponse {
  success: boolean;
  id: number;
}

export interface EmptyResponse {
}

export interface LoginRequest {
  email?: string | undefined;
  userName?: string | undefined;
  password: string;
  deviceName: string;
}

export interface RefreshTokensRequest {
  userId: number;
  tokenVersion: number;
  profileId: number;
  roleName: string;
}

export interface ForgotPasswordRequest {
  email?: string | undefined;
  userName?: string | undefined;
}

export interface ResetPasswordRequest {
  actionToken: string;
  password: string;
}

export interface LogoutRequest {
  userId: number;
}

export interface TerminateAllSessionsRequest {
  userId: number;
}

export interface TokenResponse {
  accessToken: string;
  refreshToken: string;
}

export interface AuthServiceClient {
  confirmRegistration(request: ConfirmRegistrationRequest): Observable<ActionResponse>;

  login(request: LoginRequest): Observable<TokenResponse>;

  refreshTokens(request: RefreshTokensRequest): Observable<TokenResponse>;

  forgotPassword(request: ForgotPasswordRequest): Observable<ActionResponse>;

  resetPassword(request: ResetPasswordRequest): Observable<ActionResponse>;

  logout(request: LogoutRequest): Observable<ActionResponse>;

  terminateAllSessions(request: TerminateAllSessionsRequest): Observable<EmptyResponse>;
}

export interface AuthServiceController {
  confirmRegistration(
    request: ConfirmRegistrationRequest,
  ): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  login(request: LoginRequest): Promise<TokenResponse> | Observable<TokenResponse> | TokenResponse;

  refreshTokens(request: RefreshTokensRequest): Promise<TokenResponse> | Observable<TokenResponse> | TokenResponse;

  forgotPassword(request: ForgotPasswordRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  resetPassword(request: ResetPasswordRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  logout(request: LogoutRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  terminateAllSessions(
    request: TerminateAllSessionsRequest,
  ): Promise<EmptyResponse> | Observable<EmptyResponse> | EmptyResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "confirmRegistration",
      "login",
      "refreshTokens",
      "forgotPassword",
      "resetPassword",
      "logout",
      "terminateAllSessions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
