export enum AuthCommand {
  CREATE_ACTION_TOKEN = "CREATE_ACTION_TOKEN",
  CREATE_TOKEN_PAIR = "CREATE_TOKEN_PAIR",
}
export enum AuthEvent {
  ACTION_TOKEN_CREATED = "ACTION_TOKEN_CREATED",
  CANDIDATE_VERIFIED = "CANDIDATE_VERIFIED",
  TOKEN_PAIR_CREATED = "TOKEN_PAIR_CREATED",
  USER_LOGINED = "USER_LOGINED",
  USER_LOGOUTED = "USER_LOGOUTED",
  PASSWORD_APPROWED = "PASSWORD_APPROWED",
}

export enum AuthSubType {
  LOGINED = "logined",
  LOGOUTED = "logouted",
  PASSWORD_APPROWED = "password.approwed",
}

export enum ActionTokenType {
  REGISTRATION = "REGISTRATION",
  LOGIN = "LOGIN",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
}
