export enum TokenType {
  ACTION_TOKEN = "ACTION_TOKEN",
  ACCESS_TOKEN = "ACCESS_TOKEN",
  REFRESH_TOKEN = "REFRESH_TOKEN",
}

export enum LoginType {
  REGISTRATION_FLOW = "REGISTRATION_FLOW",
  LOGIN_FLOW = "LOGIN_FLOW",
}
