// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface SubscribeRequest {
  userId: number;
  scope: string;
}

export interface ServiceResponse {
  step: string;
  progress: number;
  message: string;
  registration?: RegistrationPayload | undefined;
  order?: OrderPayload | undefined;
}

export interface OrderStream {
  step: string;
  progress: number;
  message: string;
  payload?: OrderPayload | undefined;
}

export interface OrderPayload {
  candidates?: CandidatesList | undefined;
  newJob?: CleanerJob | undefined;
  orderId: number;
}

export interface CandidatesList {
  list: CleanerCandidate[];
}

export interface RegistrationStream {
  step: string;
  progress: number;
  message: string;
  payload?: RegistrationPayload | undefined;
}

export interface RegistrationPayload {
  accessToken: string;
  refreshToken: string;
}

export interface ServiceStreamResponse {
  type: string;
  orderId?: number | undefined;
  subType: string;
  status: string;
  message: string;
  payload?: UniversalPayload | undefined;
}

export interface UniversalPayload {
  customer?: CustomerPayload | undefined;
  cleaner?: CleanerPayload | undefined;
  chat?: ChatPayload | undefined;
}

export interface CleanerPayload {
  newJob?: CleanerJob | undefined;
}

export interface CleanerJob {
  id: number;
  cleanerProfileId: number;
  orderId: number;
  status: string;
  createdAt: string;
}

export interface CustomerPayload {
  candidates?: CandidateList | undefined;
  invitation?: CleanerJob | undefined;
}

export interface CandidateList {
  list: CleanerCandidate[];
}

export interface CleanerCandidate {
  id: number;
  firstName: string;
  lastName: string;
  experienceYears: number;
  rating: number;
  createdAt: string;
}

export interface ChatPayload {
  roomId: string;
  partner?: ChatPartner | undefined;
  message?: ChatMessage | undefined;
}

export interface ChatMessage {
  text: string;
  createdAt: string;
}

export interface ChatPartner {
  id: number;
  firstName: string;
  lastName: string;
  phone: string;
  rating?: number | undefined;
  isOnline: boolean;
}

export interface NotificationServiceClient {
  subscribeNotifications(request: SubscribeRequest): Observable<ServiceResponse>;
}

export interface NotificationServiceController {
  subscribeNotifications(request: SubscribeRequest): Observable<ServiceResponse>;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["subscribeNotifications"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
