export enum GRPC_PRISMA_SERVICES {
  USER = 'USER_SERVICE',
  ROLE = 'ROLE_SERVICE',
  AUTH = 'AUTH_SERVICE',
  CUSTOMER = 'CUSTOMER_SERVICE',
  CLEANER = 'CLEANER_SERVICE',
  ORDER = 'ORDER_SERVICE',
  CHAT = 'CHAT_SERVICE',
}
export enum GRPC_NON_PRISMA_SERVICES {
  REGISTRATION = 'REGISTRATION_SERVICE',
  DISPATCHER_ORDER = 'DISPATCHER_ORDER',
}

export enum GRPC_MONGO_SERVICES {
  PROJECTION = 'PROJECTION_SERVICE',
}
