export enum TokenType {
  ACTION_TOKEN = 'ACTION_TOKEN',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}

export enum ActionTokenType {
  REGISTRATION = 'REGISTRATION',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}
