syntax = "proto3";

package notification;

service NotificationService {
    rpc SubscribeNotifications (SubscribeRequest) returns (stream ServiceResponse);
}

message SubscribeRequest {
    int32 userId = 1;
    string scope = 2;
}

message ServiceResponse {
  string step = 1;
  int32 progress = 2;
  string message = 3;
  oneof payload {
     RegistrationPayload registration = 4;
     OrderPayload order = 5;
  }
}
message OrderStream{
    string step = 1;
    int32 progress = 2;
    string message =3;
    optional OrderPayload payload = 4;
}
message OrderPayload{
    optional CandidatesList candidates = 1;
    optional CleanerJob newJob = 2;
    int32 orderId = 3;
}
message CandidatesList {
    repeated CleanerCandidate list = 1;
}
message RegistrationStream{
    string step = 1;
    int32 progress = 2;
    string message =3;
    optional RegistrationPayload payload = 4;
}
message RegistrationPayload {
    string accessToken = 1;
    string refreshToken = 2;
}

message ServiceStreamResponse {
    string type = 1;
    optional int32 orderId = 2;
    string subType =3;
    string status = 4;
    string message = 5;
    optional UniversalPayload payload = 6;
  }

message UniversalPayload {
  oneof data {
    CustomerPayload customer = 1;
    CleanerPayload cleaner= 2;
    ChatPayload chat = 3;
  }
}
  
       
message CleanerPayload {
    optional CleanerJob newJob = 1;
}
message CleanerJob{
    int32 id = 1;
    int32 cleanerProfileId = 2;
    int32 orderId = 3;
    string status = 4;
    string createdAt = 5;
}
message CustomerPayload {
  optional CandidateList candidates = 1;
  optional CleanerJob invitation = 2;

}
   
message CandidateList {
   repeated CleanerCandidate list = 1;

}
message CleanerCandidate {
    int32 id = 1;
    string firstName = 2;
    string lastName = 3;
    int32 experienceYears = 4;
    int32 rating = 5;
    string createdAt = 6;
}


message ChatPayload {
    string roomId = 1;
        optional ChatPartner partner = 2;
        optional ChatMessage message = 3;
    
}
message ChatMessage {
    string text = 1;
    string createdAt = 2 ;
}
message ChatPartner {
    int32 id = 1;
    string firstName = 2;
    string lastName = 3;
    string phone = 4;
    optional int32 rating =5;
    bool isOnline = 6;
}

