syntax = "proto3";

package user;

service UserService {
  rpc CreateCandidate(CreateRequest) returns (ActionResponse);
  rpc FindPrivateUser(FindOneUserRequest) returns (PrivateUser);
  rpc FindPublicUser(FindOneUserRequest) returns (PublicUser);
}
message PublicUser {
  int32 id = 1;
  string userName = 2;
  string email = 3;
}
message PrivateUser {
  int32 id = 1;
  string userName = 2;
  string role = 3;
  int32 tokenVersion = 4;
  string password = 5;
}
message FindOneUserRequest {
  optional string userName = 1;
  optional string email = 2;
  optional int32 id = 3;
}
message ActionResponse {
  bool success = 1;
  int32 id = 2;
}
message CreateRequest {
  string email = 1;
  string userName = 2;    
  string password = 3;
  string role = 4;
}
