ALTER TABLE customer.outbox 
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id SET DATA TYPE INT USING NULL;

ALTER TABLE customer.profile 
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id SET DATA TYPE INT USING NULL;