export enum OrderCommands {
  CREATE_ORDER = "CREATE_ORDER",
  SELECT_CLEANER = "SELECT_CLEANER",
  CREATE_INVITATIONS = "CREATE_INVITATIONS",
  CLEANER_NOT_FOUND = "CLEANER_NOT_FOUND",
  UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS",
  CLEANER_ACCEPTED = "CLEANER_ACCEPTED",
}

export enum OrderEvents {
  ORDER_CREATED = "ORDER_CREATED",
  CLEANER_SELECTED = "CLEANER_SELECTED",
  CLEANER_BOUND_TO_ORDER = "CLEANER_BOUND_TO_ORDER",
}
