// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface ServiceCommandResponse {
  status: string;
  id: number;
}

export interface HistoryResponce {
  orderHistory: OrderHistory[];
}

export interface OrederInvitations {
}

export interface HideCleanerRequest {
  cleanerProfileId: number;
  customerId: number;
  orderId: number;
}

export interface InviteCleanerRequest {
  cleanerProfileId: number;
  customerId: number;
  orderId: number;
}

export interface OrderHistory {
  id: string;
  aggregateId: number;
  aggregateType: string;
}

export interface GetOrderRequest {
  id: number;
}

export interface CreateNewOrderRequest {
  customerId: number;
  zipCode: number;
  city: string;
  dayOfWeek: number;
  fromTime: string;
  toTime: string;
  clarifications: string;
}

export interface BaseOrder {
  id: number;
  customerId: number;
  zipCode: number;
  city: string;
  dayOfWeek: number;
  fromTime: string;
  toTime: string;
  status: string;
  cleanerId: number;
  clarifications: string;
}

export interface OrderServiceClient {
  createOrder(request: CreateNewOrderRequest): Observable<ServiceCommandResponse>;

  selectCleaner(request: InviteCleanerRequest): Observable<ServiceCommandResponse>;

  getOrderById(request: GetOrderRequest): Observable<BaseOrder>;

  getOrderHistory(request: GetOrderRequest): Observable<OrderHistory>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateNewOrderRequest,
  ): Promise<ServiceCommandResponse> | Observable<ServiceCommandResponse> | ServiceCommandResponse;

  selectCleaner(
    request: InviteCleanerRequest,
  ): Promise<ServiceCommandResponse> | Observable<ServiceCommandResponse> | ServiceCommandResponse;

  getOrderById(request: GetOrderRequest): Promise<BaseOrder> | Observable<BaseOrder> | BaseOrder;

  getOrderHistory(request: GetOrderRequest): Observable<OrderHistory>;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "selectCleaner", "getOrderById", "getOrderHistory"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
