
syntax = "proto3";
package user_service;

service UserService {
  rpc CheckUserUniqueness(CheckUniqueUser) returns (Empty);
  rpc CreateUser(CreateUserRequest) returns (Empty);
  rpc GetUserPublic(UserIdentify) returns(PublicUserRes);
  rpc GetUserForAuth (UserIdentify) returns (PrivateUserRes);
  rpc UpdateUserPassword(UpdateUserPasswordRequest) returns (UserServiceResponce);
}
message Empty {
}

message PrivateUserRes{
  int32 id = 1;
  string userName = 3;
  int32 tokenVersion = 8;
  string roleName = 9;
  string password = 11;
}
message PublicUserRes{
  int32 id = 1;
  string email = 2;
  string userName = 3;
  bool isEmailVerified = 4;
  bool isActive = 5;
  string createdAt = 6;
  string updatedAt = 7;
  int32 tokenVersion = 8;
  string roleName = 9;
  string phoneNumber = 10;
}
message UpdateUserPasswordRequest{
  int32 userId = 1;
  string password = 2;
}
message CreateUserRequest{
  string email = 1;
  string userName = 2;
  string password = 3;
  string role = 4;
}
message UserServiceResponce {
  bool success=1;
  string message=2;
  oneof response{
    Data data = 3;
    ErrorDetails error=4;
  }
}
message Data{
  oneof responce{
    GetUserForAuth getUserForAuth = 2;
    GetUserPublicReq getPublicUser = 3;
  }
}
message GetUserForAuth{
  int32 id = 1;
  string userName = 2;
  string roleName = 3;
  string password = 4;
  int32 tokenVersion = 5;
}
message ErrorDetails{
  int32 code = 1;     
  string field = 2;       
  string context = 4;
}
message CheckUniqueUser{
  oneof request {
    string email = 1;
    string userName = 2;
  }
    
}
message UserIdentify { 
  oneof request{
    int32 id = 1;
    string email = 2;
    string userName = 3;
  }
}
message GetUserPublicReq {
  int32 id = 1;
  string email = 2;
  string userName = 3;
  bool isEmailVerified = 4;
  bool isActive = 5;
  string createdAt = 6;
  string updatedAt = 7;
  int32 tokenVersion = 8;
  string roleName = 9;
  string phoneNumber = 10;
}