// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: cleaner.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface SubscribeRequest {
  /** Добавляем сюда ID */
  profileId: number;
}

export interface ActionResponse {
  success: boolean;
  id: number;
}

export interface PersonalNotification {
  /** Например: "OPEN_CHAT" */
  type: string;
  /** Можно добавить любые другие поля */
  roomId: string;
}

/** ТО САМОЕ СООБЩЕНИЕ ДЛЯ СТРИМА */
export interface ServiceStreamResponse {
  type: string;
  jobData?: Job | undefined;
  chatData?: Chat | undefined;
  summaryData?: number | undefined;
}

export interface Chat {
  orderId: number;
  roomId: string;
  cleanerId: number;
  customerId: number;
}

export interface JobsList {
  items: Job[];
}

export interface Empty {
}

export interface UpdateSlotRequest {
  id: number;
  scheduleDayId: number;
  startTime: string;
  endTime: string;
  isAvailable: boolean;
}

export interface HandleJobRequest {
  cleanerProfileId: number;
  jobId: number;
}

export interface GetterProfileRequest {
  userId?: number | undefined;
  id?: number | undefined;
}

export interface GetterOthers {
  cleanerProfileId: number;
}

export interface Job {
  id: number;
  cleanerProfileId: number;
  orderId: number;
  status: string;
  createdAt: string;
}

export interface JobRequest {
  pastJobs: Job[];
}

export interface ScheduleSlot {
  /** "09:00" */
  startTime: string;
  /** "12:00" */
  endTime: string;
}

export interface SaveDayScheduleRequest {
  cleanerProfileId: number;
  /** 0-6 */
  dayOfWeek: number;
  slots: ScheduleSlot[];
}

export interface SlotResponse {
  id: number;
  scheduleDayId: number;
  /** "09:00" */
  startTime: string;
  /** "12:00" */
  endTime: string;
  isAvailable: boolean;
}

export interface UpdateProfileRequest {
  id: number;
  firstName?: string | undefined;
  lastName?: string | undefined;
  city?: string | undefined;
  zipCode?: number | undefined;
}

export interface CleanerProfiles {
  id: number;
  userId: number;
}

export interface CleanerProfile {
  id: number;
  userId: number;
  firstName: string;
  lastName: string;
  city: string;
  zipCode: number;
  experienceYears: number;
  rating: number;
  busy: boolean;
}

export interface CleanerServiceResponse {
  success: boolean;
  message: string;
  data?: Data | undefined;
  error?: ErrorDetails | undefined;
}

export interface Data {
  schedule?: SchedulesData | undefined;
  profile?: CleanerProfile | undefined;
  profiles?: ProfilesData | undefined;
  jobs?: JobsData | undefined;
  job?: CleanerJob | undefined;
  slot?: SlotResponse | undefined;
}

export interface ScheduleDay {
  id: number;
  cleanerProfileId: number;
  dayOfWeek: number;
  slots: SlotResponse[];
}

export interface SchedulesData {
  schedule: ScheduleDay[];
}

export interface ProfilesData {
  items: CleanerProfiles[];
}

export interface JobsData {
  items: CleanerJob[];
}

export interface CleanerJob {
  id: number;
  cleanerProfileId: number;
  orderId: number;
  status: string;
  paymentStatus: string;
  createdAt: string;
}

/** Это обертка для возврата списка */
export interface GetJobsResponse {
  jobs: CleanerJob[];
}

export interface ErrorDetails {
  code: number;
  field: string;
  context: string;
}

export interface CleanerServiceClient {
  getJobs(request: GetterOthers): Observable<Job>;

  getReviews(request: GetterOthers): Observable<CleanerServiceResponse>;

  getSchedule(request: GetterOthers): Observable<ScheduleDay>;

  getProfile(request: GetterProfileRequest): Observable<CleanerProfile>;

  updateProfile(request: UpdateProfileRequest): Observable<ActionResponse>;

  saveDaySchedule(request: SaveDayScheduleRequest): Observable<ActionResponse>;

  updateSlot(request: UpdateSlotRequest): Observable<SlotResponse>;

  acceptJob(request: HandleJobRequest): Observable<Empty>;

  declineJob(request: HandleJobRequest): Observable<Empty>;
}

export interface CleanerServiceController {
  getJobs(request: GetterOthers): Observable<Job>;

  getReviews(
    request: GetterOthers,
  ): Promise<CleanerServiceResponse> | Observable<CleanerServiceResponse> | CleanerServiceResponse;

  getSchedule(request: GetterOthers): Observable<ScheduleDay>;

  getProfile(request: GetterProfileRequest): Promise<CleanerProfile> | Observable<CleanerProfile> | CleanerProfile;

  updateProfile(request: UpdateProfileRequest): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  saveDaySchedule(
    request: SaveDayScheduleRequest,
  ): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  updateSlot(request: UpdateSlotRequest): Promise<SlotResponse> | Observable<SlotResponse> | SlotResponse;

  acceptJob(request: HandleJobRequest): Promise<Empty> | Observable<Empty> | Empty;

  declineJob(request: HandleJobRequest): Promise<Empty> | Observable<Empty> | Empty;
}

export function CleanerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getJobs",
      "getReviews",
      "getSchedule",
      "getProfile",
      "updateProfile",
      "saveDaySchedule",
      "updateSlot",
      "acceptJob",
      "declineJob",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CleanerService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CleanerService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CLEANER_SERVICE_NAME = "CleanerService";
