export enum CleanerCommands {
  RESERV_CLEANERS = "RESERV_CLEANERS_CMD",
  INVITE_CLEANER = "INVITE_CLEANER_CMD",
  ACCEPT_ORDER = "ACCEPT_ORDER",
  DECLINE_CLEANER = "DECLINE_CLEANER",
  CREATE_CLEANER = "CREATE_CLEANER",
}

export enum CleanerEvents {
  PROFILE_CREATED = "PROFILE_CREATED",
  CLEANERS_RESERVED = "CLEANERS_RESERVED",
  CLEANER_ACCEPTED = "CLEANER_ACCEPTED",
  CLEANER_DECLINED = "CLEANER_DECLINED",
  CLEANER_NOT_FOUND = "CLEANER_NOT_FOUND",
  CLEANER_INVITED = "CLEANER_INVITED",
}
